version: 2
jobs:
  build:
    docker:
      - image: abeaumont/competitive-programming:1.5.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            eval `opam config env`
						alias glpsol='/usr/bin/glpsol $* > /dev/null'
            python test.py
