version: 2
jobs:
  build:
    docker:
      - image: abeaumont/competitive-programming:2.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            ./test.py
