version: 2
jobs:
  build:
    docker:
      - image: abeaumont/competitive-programming:1.3.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            eval `opam config env`
            python test.py
