version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            python test.py
