version: 2
jobs:
  build:
    docker:
      - image: abeaumont/competitive-programming:0.0.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            python test.py
